xfryzp00.pdf: xfryzp00.tex
	pdflatex xfryzp00.tex
	bibtex xfryzp00
	pdflatex xfryzp00.tex
	pdflatex xfryzp00.tex

clean:
	rm -f xfryzp00.aux xfryzp00.toc xfryzp00.log xfryzp00.bbl xfryzp00.blg xfryzp00.out
