#
# Soubor:  Makefile
# Datum:   3.3.2012
# Autor:   Pavel Fryz, xfryzp00@stud.fit.vutbr.cz, FIT
# Projekt: Webovy klient
#

CPPFLAGS=-std=c++98 -pedantic

webinfo: webinfo.cpp webinfo.h
	g++ $(CPPFLAGS) -o webinfo webinfo.cpp

clean:
	rm -f *.o webinfo

